colors:
  # Default colors
  primary:
    background: '#080812'
    foreground: '#c1c1c3'

    dim_foreground:    '#57576a'
    bright_foreground: '#43546a'
    dim_background:    '#57576a' # not sure
    bright_background: '#080812' # not sure

  # Cursor colors
  # cursor:
    # text:   '#c1c1c3'
    # cursor: '#080812'

  # Normal colors
  normal:
    black:   '#080812'
    red:     '#1c2334'
    green:   '#242433'
    yellow:  '#24243c'
    blue:    '#292c3c'
    magenta: '#2b2d47'
    cyan:    '#34314b'
    white:   '#c1c1c3'

  # Bright colors
  bright:
    black:   '#57576a'
    red:     '#473e6a'
    green:   '#444474'
    yellow:  '#4d447b'
    blue:    '#43546a'
    magenta: '#445274'
    cyan:    '#545481'
    white:   '#c1c1c3'

  # Dim colors
  dim:
    black:   '#080812'
    red:     '#1c2334'
    green:   '#242433'
    yellow:  '#24243c'
    blue:    '#292c3c'
    magenta: '#2b2d47'
    cyan:    '#34314b'
    white:   '#c1c1c3'
